### ISSUE TITLE
"App\Controller\FormSearchController" has no container set

### ISSUE THREAD

**Issue by Aeen** [dbwebb-se/mvc#46]
Jag håller på med övningen i kmom02. Jag har kopierat koden från samma exempel som Mos använde i föreläsningen igår (5/4). På Search så får jag följande felmeddelande när jag försöker besöka sidan.

"App\Controller\FormSearchController" has no container set, did you forget to define it as a service subscriber?

Varför blir det så och vad behöver jag göra?

**Comment by Aeen** [comment]
Lösningen var så enkel som att jag råkat döpa "FormSearchController" till "Controller\FormSe**ra**chController".

**Comment by mosbth** [comment]
Gott!
